### ISSUE TITLE
No group topic

### ISSUE THREAD

**Issue by kev-the-dev** [RustyBamboo/Programming-project#1]
Post your ideas for a topic for this project and we will discuss

**Comment by RustyBamboo** [comment]
Upload an image, and it'll animate the image/scene...
Example: Upload pic of tree... Then the tree branches move with rain particles or something...

**Comment by kev-the-dev** [comment]
Topic: Small autonomous car. A hoby-RC car sized robot that can move around to waypoints and avoid obstacles.

**Comment by kev-the-dev** [comment]
Topic: A 2D video game

Features: path finding AI, physics simulation (gravity,wind), Uses http://www.sfml-dev.org/ library

Pros: Very object oriented, easy to separate tasks

**Comment by kev-the-dev** [comment]
Topic: A database.
Potential features: use SQL, interface over HTTP, cache data in memory and in custom file format

**Comment by kev-the-dev** [comment]
Topic: A secure messaging system
Potential Features: implement our own/ an existing encryption format, web interface, CLI

**Comment by kev-the-dev** [comment]
Topic: A group election system
Potential Features: web interface, custom voting algorithm (winner take all, single transferable vote), security (encryption/authentication), statistical analysis (demographic info, etc)

**Comment by RustyBamboo** [comment]
We decided on make a Geometry-shaped game.
