### ISSUE TITLE
Add rays (guns)

### ISSUE THREAD

**Issue by kev-the-dev** [RustyBamboo/Programming-project#6]

**Comment by RustyBamboo** [comment]
This probably should be done in the rectangle class in the entities folder.
 Inside tick function have the velocity add to the position. Maybe add how long it can live for...
`sf::Clock clock;`
`if(clock.getElapsedTime().asMilliseconds() > thelifespan) { clock.restart(); delete it and stuff }`

This one is really dependent on everything else, so I'm not sure exactly the easiest way to add it. (This is also reliant on the network code and stuff... So I'll get back to this)
